spring.application.name=producto-service

server.port=0

spring.datasource.url=jdbc:mysql://mysql-product-db:3306/producto_urban_db_golden
spring.datasource.username=root
spring.datasource.password=fernandez77

###################
##CUSTOM SETTINGS##
###################
app.queue.name=log-queue

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
